[default_session]
startup_command = "nvim"

[[session]]
name = "btop"
path = "~/workspace/"
startup_command = "btop"

[[session]]
name = "fish"
path = "~/.config/fish/"
startup_command = "nvim config.fish"

[[session]]
name = "tmux"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"
