[default_session]
startup_command = "nvim"

[[session]]
name = "btop"
path = "~/workspace/"
startup_command = "btop"

[[session]]
name = "fish config"
path = "~/.config/fish/"
startup_command = "nvim config.fish"

[[session]]
name = "sesh config"
path = "~/.config/sesh/"
startup_command = "nvim sesh.toml"

[[session]]
name = "neovim config"
path = "~/.config/nvim/"
startup_command = "nvim "

[[session]]
name = "notes"
path = "~/workspace/notes/"
startup_command = "nvim -c ObsidianToday"

[[session]]
name = "todos"
path = "~/workspace/todos/"
startup_command = "nvim todos.md"


[[session]]
name = "tmux config"
path = "~/.config/tmux/"
startup_command = "nvim tmux.conf"

[[session]]
name = "k8s workspace"
path = "~/workspace/mercari/"
startup_command = "k9s"


